// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/impuestos": {
            "get": {
                "description": "Return list of impuestos.",
                "tags": [
                    "impuestos"
                ],
                "summary": "Get All impuestos.",
                "responses": {
                    "200": {
                        "description": "Impuestos recuperados exitosamente.",
                        "schema": {
                            "type": "obejct"
                        }
                    }
                }
            },
            "post": {
                "description": "Save impuestos data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "impuestos"
                ],
                "summary": "Create impuestos",
                "parameters": [
                    {
                        "description": "Create impuestos",
                        "name": "impuestos",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/impuesto.AddImpuestoRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Impuesto creada exitosamente.",
                        "schema": {
                            "$ref": "#/definitions/models.Impuesto"
                        }
                    }
                }
            }
        },
        "/impuestos/{id}": {
            "get": {
                "description": "Return the tahs whoes marId valu mathes id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "impuestos"
                ],
                "summary": "Get Single Impuestos by id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get impuestos by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Impuesto encontrada exitosamente.",
                        "schema": {
                            "$ref": "#/definitions/models.Impuesto"
                        }
                    }
                }
            },
            "put": {
                "description": "Update impuestos data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "impuestos"
                ],
                "summary": "Update impuestos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "update Impuestos by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update tags",
                        "name": "impuestos",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/impuesto.UpdateImpuestoRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Impuesto actualizada exitosamente.",
                        "schema": {
                            "$ref": "#/definitions/models.Impuesto"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove Impuestos data by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "impuestos"
                ],
                "summary": "Delete Impuestos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get Impuestos by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Impuesto borrada exitosamente.",
                        "schema": {
                            "$ref": "#/definitions/models.Impuesto"
                        }
                    }
                }
            }
        },
        "/marks": {
            "get": {
                "description": "Return list of marks.",
                "tags": [
                    "marks"
                ],
                "summary": "Get All marks.",
                "responses": {
                    "200": {
                        "description": "Marks recuperadas exitosamente.",
                        "schema": {
                            "type": "obejct"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "parameters": [
                    {
                        "description": "Update tags",
                        "name": "marks",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mark.UpdateMarkBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mark updated successfully.",
                        "schema": {
                            "$ref": "#/definitions/models.Mark"
                        }
                    }
                }
            },
            "post": {
                "description": "Save marks data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "Create marks",
                "parameters": [
                    {
                        "description": "Create marks",
                        "name": "marks",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mark.AddMarkBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully created mark.",
                        "schema": {
                            "$ref": "#/definitions/models.Mark"
                        }
                    }
                }
            }
        },
        "/marks/{id}": {
            "get": {
                "description": "Return the tahs whoes marId valu mathes id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "Get Single Marks by id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get marks by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mark found successfully.",
                        "schema": {
                            "$ref": "#/definitions/models.Mark"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove marks data by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "Delete marks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get marks by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mark successfully erased.",
                        "schema": {
                            "$ref": "#/definitions/models.Mark"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "impuesto.AddImpuestoRequestBody": {
            "type": "object",
            "properties": {
                "imp_nombre": {
                    "type": "string"
                },
                "imp_tasa": {
                    "type": "number"
                }
            }
        },
        "impuesto.UpdateImpuestoRequestBody": {
            "type": "object",
            "properties": {
                "imp_nombre": {
                    "type": "string"
                },
                "imp_tasa": {
                    "type": "number"
                }
            }
        },
        "mark.AddMarkBody": {
            "type": "object",
            "properties": {
                "mar_id": {
                    "type": "integer"
                },
                "mar_name": {
                    "type": "string"
                }
            }
        },
        "mark.UpdateMarkBody": {
            "type": "object",
            "properties": {
                "mar_id": {
                    "type": "integer"
                },
                "mar_name": {
                    "type": "string"
                }
            }
        },
        "models.Impuesto": {
            "type": "object",
            "properties": {
                "imp_id": {
                    "type": "integer"
                },
                "imp_nombre": {
                    "type": "string"
                },
                "imp_tasa": {
                    "type": "number"
                }
            }
        },
        "models.Mark": {
            "type": "object",
            "properties": {
                "mar_id": {
                    "type": "integer"
                },
                "mar_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Tag Service API",
	Description:      "A Tag service API in Go using Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
